namespace StudentEnrollment.API.DTOs.Enrollment
{
    // Don't want to expose Id for Posting, as it will be generated by data context (database)
    public class CreateEnrollmentDto
    {
        public int CourseId { get; set; }
        public int StudentId { get; set; }
    }
}
