using StudentEnrollment.API.DTOs.Course;
using StudentEnrollment.API.DTOs.Student;

namespace StudentEnrollment.API.DTOs.Enrollment
{
    public class EnrollmentDto
    {
        public int Id { get; set; }
        public int CourseId { get; set; }
        public int StudentId { get; set; }

        public virtual CourseDto Course { get; set; }
        public virtual StudentDto Student { get; set; }

    }

    // Don't want to expose Id for Posting, as it will be generated by data context (database)
    public class CreateEnrollmentDto
    {
        public int CourseId { get; set; }
        public int StudentId { get; set; }
    }

    // Probably never used, just for discussion
    public class CreateCompleteEnrollmentDto
    {
        public int CourseId { get; set; }
        public int StudentId { get; set; }
        public virtual CourseDto Course { get; set; }
        public virtual StudentDto Student { get; set; }
    }
}
